### ISSUE TITLE
Rebuild of binaries failed

### ISSUE THREAD

**Issue by xsilvertom** [ondrejholecek/sniftran#2]
Binaries folders and files time states 4y old.
And so I guessed that [892ba19](https://github.com/ondrejholecek/sniftran/pull/1/commits/892ba191121ab5ea30c045b7cb555b2e11a33658) "support packet prefixes like "[FIM01]" that are generated by 6k7k blades" is not incorporated into existing binaries here.
Tried to make those binaries for myself, but it ended with following error:

`xsilver@SILVERSTONE:sniftran-master $make
pyinstaller --onefile sniftran.py
70 INFO: PyInstaller: 5.3
70 INFO: Python: 3.8.10
84 INFO: Platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.29
85 INFO: wrote /home/xsilver/tempik/sniftran-master/sniftran.spec
97 INFO: UPX is not available.
101 INFO: Extending PYTHONPATH with paths
['/home/xsilver/tempik/sniftran-master']
535 INFO: checking Analysis
536 INFO: Building Analysis because Analysis-00.toc is non existent
536 INFO: Initializing module dependency graph...
538 INFO: Caching module graph hooks...
547 INFO: Analyzing base_library.zip ...
3643 INFO: Processing pre-find module path hook distutils from '/home/xsilver/.local/lib/python3.8/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
3645 INFO: distutils: retargeting to non-venv dir '/usr/lib/python3.8'
6297 INFO: Caching module dependency graph...
6429 INFO: running Analysis Analysis-00.toc
6582 INFO: Analyzing /home/xsilver/tempik/sniftran-master/sniftran.py

Syntax error in /home/xsilver/tempik/sniftran-master/sniftran.py
  File "/home/xsilver/tempik/sniftran-master/sniftran.py", line 198
     print "WARNING: cannot recognize time format"
           ^
 SyntaxError: Missing parentheses in call to 'print'. Did you mean print("WARNING: cannot recognize time format")?

make: *** [Makefile:10: sniftran] Error 1`

**Comment by ondrejholecek** [comment]
caused by using pyinstaller from python3 to "compile" code written in python2

since it is quite complicated to get pyinstaller@2 for all systems nowadays, the merge above converts code to python3
